#!/usr/bin/env python3

import sys
import math

def factorize(number):
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            return i, number // i
    return number, 1

def main(file_path):
    with open(file_path, 'r') as file:
        numbers = [int(line.strip()) for line in file]

    for number in numbers:
        factor1, factor2 = factorize(number)
        print(f"{number}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    file_path = sys.argv[1]
    main(file_path)

